# 文件管理系统配置文件
# 支持环境变量覆盖和多种配置格式

# 通用配置
app_name: "文件管理系统"
version: "2.0.0"

# 开发环境配置
development:
  debug_mode: true
  log_level: DEBUG
  server_host: "127.0.0.1"
  server_port: 8888
  
  # 开发环境允许更多调试信息
  log_enable_console: true
  log_enable_file: true
  log_enable_json: true
  log_enable_color: true
  
  # 开发环境性能监控
  enable_performance_monitoring: true
  performance_slow_threshold: 0.5
  
  # 开发环境安全设置
  enable_security_logging: true
  security_log_level: DEBUG
  
  # 开发环境缓存设置
  cache_enabled: true
  cache_default_ttl: 60  # 1分钟
  
  # 开发环境文件限制
  max_file_size: 1073741824  # 1GB
  forbidden_extensions: [".exe", ".bat", ".cmd", ".com", ".pif", ".scr"]
  allow_executable_files: false

# 生产环境配置
production:
  debug_mode: false
  log_level: WARNING
  server_host: "0.0.0.0"
  server_port: 8888
  
  # 生产环境日志设置
  log_enable_console: false
  log_enable_file: true
  log_enable_json: true
  log_enable_color: false
  
  # 生产环境性能监控
  enable_performance_monitoring: true
  performance_slow_threshold: 2.0
  
  # 生产环境安全设置
  enable_security_logging: true
  security_log_level: WARNING
  
  # 生产环境缓存设置
  cache_enabled: true
  cache_default_ttl: 1800  # 30分钟
  cache_max_items: 50000
  
  # 生产环境文件限制
  max_file_size: 10737418240  # 10GB
  forbidden_extensions: [".exe", ".bat", ".cmd", ".com", ".pif", ".scr", ".vbs", ".js", ".jar"]
  allow_executable_files: false

# 测试环境配置
testing:
  debug_mode: true
  log_level: DEBUG
  server_host: "127.0.0.1"
  server_port: 8889
  
  # 测试环境特殊设置
  log_enable_console: true
  log_enable_file: false
  cache_enabled: false
  enable_performance_monitoring: false

# Redis配置
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null
  ssl: false
  
  # 连接池配置
  pool_config:
    max_connections: 20
    retry_on_timeout: true
    socket_keepalive: true
    health_check_interval: 30

# 前端配置
frontend_config:
  app_name: "文件管理系统"
  default_view: "list"
  page_size: 50
  show_hidden: false
  enable_drag_drop: true
  enable_preview: true
  theme_color: "#4a6fa5"
  secondary_color: "#6c8ebf"

# 权限配置
permissions:
  upload: true
  download: true
  delete: true
  rename: true
  create_folder: true
  admin_ops: false

# 安全配置
security:
  secret_key: null  # 自动生成
  rate_limit: "100 per minute"
  session_timeout: 3600
  max_path_length: 4096
  enable_file_type_detection: true
  
  # 文件类型验证
  forbidden_extensions: [".exe", ".bat", ".cmd", ".com", ".pif", ".scr"]
  allow_executable_files: false

# 日志配置
logging:
  level: "INFO"
  format: "json"
  file: "logs/file_manager.log"
  max_size: 10485760  # 10MB
  backup_count: 30
  
  # 高级日志设置
  enable_console: true
  enable_file: true
  enable_json: true
  enable_color: true
  rotation_when: "midnight"
  rotation_interval: 1
  compress_old: true

# 缓存配置
cache:
  enabled: true
  default_ttl: 300  # 5分钟
  max_items: 10000
  
  # 缓存策略
  strategies:
    dir_listing:
      root: 300      # 根目录5分钟
      large: 60      # 大目录1分钟
      normal: 180    # 普通目录3分钟
    file_info: 600   # 文件信息10分钟
    session: 3600    # 会话1小时
    config: 1800     # 配置30分钟

# 性能监控配置
performance:
  monitoring_enabled: true
  slow_threshold: 1.0  # 秒
  metrics_retention: 100  # 保留最近100次调用记录
  
  # 监控级别
  levels:
    critical: 0.1    # 关键函数阈值
    warning: 1.0     # 警告阈值
    info: 5.0        # 信息阈值

# 文件系统配置
filesystem:
  root_directory: null  # 自动检测
  max_file_size: 1073741824  # 1GB
  allowed_extensions: []  # 空表示允许所有
  forbidden_extensions: [".exe", ".bat", ".cmd", ".com", ".pif", ".scr"]
  
  # 文件操作限制
  max_upload_files: 100
  max_upload_size: 10737418240  # 10GB
  enable_compression: true
  
  # 预览设置
  preview:
    enabled: true
    max_preview_size: 10485760  # 10MB
    supported_types: [".txt", ".md", ".py", ".js", ".html", ".css", ".json", ".xml"]

# 上传配置
upload:
  enabled: true
  max_file_size: 1073741824  # 1GB
  max_files: 100
  chunk_size: 1048576  # 1MB分块
  
  # 上传验证
  validation:
    check_file_type: true
    check_file_size: true
    check_file_content: false
    virus_scan: false
  
  # 上传目录
  default_directory: "uploads"
  create_date_folders: true
  preserve_original_names: true

# 下载配置
download:
  enabled: true
  enable_resume: true
  chunk_size: 1048576  # 1MB分块
  
  # 下载限制
  rate_limit: "1000 per minute"
  max_concurrent: 10
  
  # 安全设置
  check_permissions: true
  log_downloads: true

# 编辑器配置
editor:
  enabled: true
  default_theme: "default"
  available_themes: ["default", "monokai", "eclipse", "dracula"]
  
  # 代码高亮
  syntax_highlighting: true
  line_numbers: true
  word_wrap: true
  
  # 编辑器功能
  features:
    search_replace: true
    auto_complete: true
    bracket_matching: true
    line_folding: true

# 通知配置
notifications:
  enabled: true
  types:
    success: true
    warning: true
    error: true
    info: true
  
  # 显示设置
  auto_hide: true
  auto_hide_delay: 5000  # 5秒
  max_notifications: 5
  
  # 错误处理
  error:
    show_details: false
    retry_enabled: true
    max_retries: 3
    retry_delay: 1000

# 监控和告警
monitoring:
  enabled: true
  
  # 健康检查
  health_check:
    enabled: true
    interval: 30  # 30秒
    timeout: 10   # 10秒
  
  # 资源监控
  resources:
    cpu_threshold: 80
    memory_threshold: 80
    disk_threshold: 90
  
  # 告警设置
  alerts:
    email: false
    webhook: false
    log: true

# 备份配置
backup:
  enabled: false
  schedule: "0 2 * * *"  # 每天凌晨2点
  retention: 7  # 保留7天
  
  # 备份内容
  content:
    config: true
    logs: true
    uploads: false
  
  # 存储设置
  storage:
    local: true
    remote: false
    compression: true

# 国际化配置
i18n:
  default_language: "zh-CN"
  supported_languages: ["zh-CN", "en-US"]
  
  # 日期时间格式
  date_format: "YYYY-MM-DD"
  time_format: "HH:mm:ss"
  timezone: "Asia/Shanghai"

# 主题配置
themes:
  default:
    name: "默认主题"
    primary_color: "#4a6fa5"
    secondary_color: "#6c8ebf"
    background_color: "#ffffff"
    text_color: "#333333"
  
  dark:
    name: "深色主题"
    primary_color: "#2c3e50"
    secondary_color: "#34495e"
    background_color: "#1a1a1a"
    text_color: "#ffffff"
  
  light:
    name: "浅色主题"
    primary_color: "#3498db"
    secondary_color: "#5dade2"
    background_color: "#f8f9fa"
    text_color: "#2c3e50"
